name: english_academy_mobile
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  country_pickers: ^2.0.0
  grouped_list: ^5.1.2
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  http: ^1.2.1
  dio: ^5.4.1
  audioplayers: ^6.0.0
  fl_chart: ^0.67.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  page_transition: ^2.1.0
  youtube_player_flutter: ^9.0.1
  flutter_stripe: ^10.1.1
  easy_paypal: ^1.0.8
  msh_checkbox: ^2.0.1
  flutter_widget_from_html: ^0.14.11
  flutter_quill: ^9.3.7
  vsc_quill_delta_to_html: ^1.0.4
  flutter_quill_extensions: ^9.3.7
  shared_preferences: ^2.2.3
  zego_uikit_prebuilt_video_conference: ^2.7.4
  animated_custom_dropdown: 3.1.1
  carousel_slider: ^4.2.1
  quickalert: ^1.1.0
  webview_flutter: ^4.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProText-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText-Regular.otf
          weight: 400
#    - family: Manrope
#      fonts:
#        - asset: assets/fonts/ManropeRegular.ttf
#          weight: 400
#        - asset: assets/fonts/ManropeBold.ttf
#          weight: 700
#        - asset: assets/fonts/ManropeSemiBold.ttf
#          weight: 600
#    - family: Urbanist
#      fonts:
#        - asset: assets/fonts/UrbanistBold.ttf
#          weight: 700
#    - family: Plus Jakarta Sans
#      fonts:
#        - asset: assets/fonts/PlusJakartaSansSemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/PlusJakartaSansMedium.ttf
#          weight: 500
#        - asset: assets/fonts/PlusJakartaSansBold.ttf
#          weight: 700
#        - asset: assets/fonts/PlusJakartaSansRegular.ttf
#          weight: 400